/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 **********************************************************************
 * This file is part of the crystalhd device driver.
 *
 * This driver is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * This driver is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this driver.  If not, see <http://www.gnu.org/licenses/>.
 **********************************************************************
 *
 * $brcm_Workfile: bchp_decode_sint_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 7/17/09 8:05p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jul 17 19:42:58 2009
 *                 MD5 Checksum         2914699efc3fb3edefca5cb4f4f38b34
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/70015/rdb/a0/bchp_decode_sint_0.h $
 * 
 * Hydra_Software_Devel/1   7/17/09 8:05p albertl
 * PR56880: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_DECODE_SINT_0_H__
#define BCHP_DECODE_SINT_0_H__

/***************************************************************************
 *DECODE_SINT_0
 ***************************************************************************/
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_ADDR     0x00800c00 /* REG_SINT_DMA_ADDR */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_LEN      0x00800c04 /* REG_SINT_DMA_LEN */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_BASE     0x00800c08 /* REG_SINT_DMA_BASE */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_END      0x00800c0c /* REG_SINT_DMA_END */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_POS     0x00800c10 /* REG_SINT_STRM_POS */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT    0x00800c14 /* REG_SINT_STRM_STAT */
#define BCHP_DECODE_SINT_0_REG_SINT_IENA         0x00800c18 /* REG_SINT_IENA */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_BITS    0x00800c1c /* REG_SINT_STRM_BITS */
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB     0x00800c20 /* REG_SINT_GET_SYMB */
#define BCHP_DECODE_SINT_0_REG_SINT_MPEG_DC      0x00800c24 /* REG_SINT_MPEG_DC */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID     0x00800c28 /* REG_SINT_DO_RESID */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO       0x00800c2c /* REG_SINT_XNZERO */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE   0x00800c30 /* REG_SINT_VEC_MBTYPE */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_RESID    0x00800c34 /* REG_SINT_VEC_RESID */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DMODE    0x00800c38 /* REG_SINT_VEC_DMODE */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOP_LD   0x00800c3c /* REG_SINT_VEC_TOP_LD */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST 0x00800c40 /* REG_SINT_VEC_DO_CONST */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF   0x00800c44 /* Deblocking Motion Vector Difference */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX   0x00800c48 /* REG_SINT_VEC_REFIDX */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF   0x00800c4c /* REG_SINT_VEC_TOPREF */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF 0x00800c50 /* REG_SINT_VEC_TOPTOPREF */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE 0x00800c54 /* REG_SINT_VEC_COL_TYPE */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID 0x00800c58 /* REG_SINT_VEC_COL_REFID */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC   0x00800c5c /* REG_SINT_VEC_TOPPIC */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO 0x00800c60 /* REG_SINT_VEC_VC1_INFO */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC   0x00800c64 /* REG_SINT_VEC_REFPIC - H.264 only */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COUNT    0x00800c68 /* REG_SINT_VEC_COUNT */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVD_FIFO 0x00800c6c /* REG_SINT_VEC_MVD_FIFO */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL  0x00800c70 /* REG_SINT_DIVX_TABSEL */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_AUX      0x00800c74 /* REG_SINT_CTL_AUX */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REGEND   0x00800c7c /* REG_SINT_VEC_REGEND */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL          0x00800c80 /* REG_SINT_CTL */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX   0x00800c84 /* REG_SINT_VLC_TOPCTX */
#define BCHP_DECODE_SINT_0_REG_SINT_SLICE_ID     0x00800c88 /* REG_SINT_SLICE_ID */
#define BCHP_DECODE_SINT_0_REG_SINT_QP           0x00800c8c /* REG_SINT_QP */
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_BASE_ADDR 0x00800c90 /* REG_SINT_TOP_BASE_ADDR */
#define BCHP_DECODE_SINT_0_REG_SINT_DIRCTX_WR_ADDR 0x00800c94 /* REG_SINT_DIRCTX_WR_ADDR */
#define BCHP_DECODE_SINT_0_REG_SINT_TOPCTX_DATA  0x00800c98 /* REG_SINT_TOPCTX_DATA */
#define BCHP_DECODE_SINT_0_REG_SINT_XFER_SYMB    0x00800c9c /* REG_SINT_XFER_SYMB */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE   0x00800ca0 /* REG_SINT_SMODE_BASE */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT   0x00800ca4 /* REG_SINT_SMODE_LEFT */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP    0x00800ca8 /* REG_SINT_SMODE_TOP */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_END    0x00800cac /* REG_SINT_SMODE_END */
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT     0x00800cb0 /* REG_SINT_CTX_INIT */
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_CTX      0x00800cb4 /* REG_SINT_TOP_CTX */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL   0x00800cb8 /* REG_SINT_VC1_TABSEL */
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA   0x00800cbc /* REG_SINT_CNST_INTRA */
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE 0x00800cc0 /* Outpic Lookup */
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_END 0x00800cfc /* REG_SINT_OPIC_MEM_END */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MEM_BASE 0x00800d00 /* Vector Memory */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MEM_END  0x00800dfc /* REG_SINT_VEC_MEM_END */

/***************************************************************************
 *REG_SINT_DMA_ADDR - REG_SINT_DMA_ADDR
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_DMA_ADDR :: Addr [31:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_ADDR_Addr_MASK             0xfffffffc
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_ADDR_Addr_SHIFT            2

/* DECODE_SINT_0 :: REG_SINT_DMA_ADDR :: reserved0 [01:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_ADDR_reserved0_MASK        0x00000003
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_ADDR_reserved0_SHIFT       0

/***************************************************************************
 *REG_SINT_DMA_LEN - REG_SINT_DMA_LEN
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_DMA_LEN :: Length [31:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_LEN_Length_MASK            0xffffffe0
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_LEN_Length_SHIFT           5

/* DECODE_SINT_0 :: REG_SINT_DMA_LEN :: reserved0 [04:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_LEN_reserved0_MASK         0x0000001f
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_LEN_reserved0_SHIFT        0

/***************************************************************************
 *REG_SINT_DMA_BASE - REG_SINT_DMA_BASE
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_DMA_BASE :: Base [31:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_BASE_Base_MASK             0xffffff00
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_BASE_Base_SHIFT            8

/* DECODE_SINT_0 :: REG_SINT_DMA_BASE :: reserved0 [07:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_BASE_reserved0_MASK        0x000000fe
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_BASE_reserved0_SHIFT       1

/* DECODE_SINT_0 :: REG_SINT_DMA_BASE :: Endian [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_BASE_Endian_MASK           0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_BASE_Endian_SHIFT          0

/***************************************************************************
 *REG_SINT_DMA_END - REG_SINT_DMA_END
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_DMA_END :: End [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_END_End_MASK               0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_DMA_END_End_SHIFT              0

/***************************************************************************
 *REG_SINT_STRM_POS - REG_SINT_STRM_POS
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_STRM_POS :: Bit_pos [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_POS_Bit_pos_MASK          0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_POS_Bit_pos_SHIFT         0

/***************************************************************************
 *REG_SINT_STRM_STAT - REG_SINT_STRM_STAT
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: reserved0 [31:19] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_reserved0_MASK       0xfff80000
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_reserved0_SHIFT      19

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: FlushInput [18:18] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_FlushInput_MASK      0x00040000
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_FlushInput_SHIFT     18

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: FlushCTX [17:17] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_FlushCTX_MASK        0x00020000
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_FlushCTX_SHIFT       17

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: Rst [16:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Rst_MASK             0x00010000
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Rst_SHIFT            16

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: reserved1 [15:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_reserved1_MASK       0x0000f000
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_reserved1_SHIFT      12

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: CtxDmaAct [11:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_CtxDmaAct_MASK       0x00000800
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_CtxDmaAct_SHIFT      11

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: MVD_AVAIL [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_MVD_AVAIL_MASK       0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_MVD_AVAIL_SHIFT      10

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: Derr [09:09] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Derr_MASK            0x00000200
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Derr_SHIFT           9

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: Serr [08:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Serr_MASK            0x00000100
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Serr_SHIFT           8

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: CgParse [07:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_CgParse_MASK         0x00000080
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_CgParse_SHIFT        7

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: CCAc [06:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_CCAc_MASK            0x00000040
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_CCAc_SHIFT           6

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: VCAc [05:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_VCAc_MASK            0x00000020
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_VCAc_SHIFT           5

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: Vact [04:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Vact_MASK            0x00000010
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Vact_SHIFT           4

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: Dact [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Dact_MASK            0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Dact_SHIFT           3

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: Sact [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Sact_MASK            0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Sact_SHIFT           2

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: Cact [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Cact_MASK            0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Cact_SHIFT           1

/* DECODE_SINT_0 :: REG_SINT_STRM_STAT :: Sval [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Sval_MASK            0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_STAT_Sval_SHIFT           0

/***************************************************************************
 *REG_SINT_IENA - REG_SINT_IENA
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_IENA :: reserved0 [31:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_IENA_reserved0_MASK            0xfffffc00
#define BCHP_DECODE_SINT_0_REG_SINT_IENA_reserved0_SHIFT           10

/* DECODE_SINT_0 :: REG_SINT_IENA :: Derr [09:09] */
#define BCHP_DECODE_SINT_0_REG_SINT_IENA_Derr_MASK                 0x00000200
#define BCHP_DECODE_SINT_0_REG_SINT_IENA_Derr_SHIFT                9

/* DECODE_SINT_0 :: REG_SINT_IENA :: Serr [08:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_IENA_Serr_MASK                 0x00000100
#define BCHP_DECODE_SINT_0_REG_SINT_IENA_Serr_SHIFT                8

/* DECODE_SINT_0 :: REG_SINT_IENA :: reserved1 [07:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_IENA_reserved1_MASK            0x000000ff
#define BCHP_DECODE_SINT_0_REG_SINT_IENA_reserved1_SHIFT           0

/***************************************************************************
 *REG_SINT_STRM_BITS - REG_SINT_STRM_BITS
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_STRM_BITS :: Stream_Bits [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_BITS_Stream_Bits_MASK     0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_STRM_BITS_Stream_Bits_SHIFT    0

/***************************************************************************
 *REG_SINT_GET_SYMB - REG_SINT_GET_SYMB
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_GET_SYMB :: reserved0 [31:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB_reserved0_MASK        0xffff0000
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB_reserved0_SHIFT       16

/* DECODE_SINT_0 :: REG_SINT_GET_SYMB :: Type [15:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB_Type_MASK             0x0000f000
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB_Type_SHIFT            12

/* DECODE_SINT_0 :: REG_SINT_GET_SYMB :: SubType [11:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB_SubType_MASK          0x00000f00
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB_SubType_SHIFT         8

/* DECODE_SINT_0 :: REG_SINT_GET_SYMB :: N [07:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB_N_MASK                0x000000ff
#define BCHP_DECODE_SINT_0_REG_SINT_GET_SYMB_N_SHIFT               0

/***************************************************************************
 *REG_SINT_MPEG_DC - REG_SINT_MPEG_DC
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_MPEG_DC :: reserved0 [31:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_MPEG_DC_reserved0_MASK         0xffffc000
#define BCHP_DECODE_SINT_0_REG_SINT_MPEG_DC_reserved0_SHIFT        14

/* DECODE_SINT_0 :: REG_SINT_MPEG_DC :: Comp [13:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_MPEG_DC_Comp_MASK              0x00003000
#define BCHP_DECODE_SINT_0_REG_SINT_MPEG_DC_Comp_SHIFT             12

/* DECODE_SINT_0 :: REG_SINT_MPEG_DC :: DC_Pred [11:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_MPEG_DC_DC_Pred_MASK           0x00000fff
#define BCHP_DECODE_SINT_0_REG_SINT_MPEG_DC_DC_Pred_SHIFT          0

/***************************************************************************
 *REG_SINT_DO_RESID - REG_SINT_DO_RESID
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: AVS [31:31] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_AVS_MASK              0x80000000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_AVS_SHIFT             31

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: DivX [30:30] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_DivX_MASK             0x40000000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_DivX_SHIFT            30

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: Use_intra_dc_vlc [29:29] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Use_intra_dc_vlc_MASK 0x20000000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Use_intra_dc_vlc_SHIFT 29

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: Short_Vid_Hdr [28:28] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Short_Vid_Hdr_MASK    0x10000000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Short_Vid_Hdr_SHIFT   28

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: Mpeg4 [27:27] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Mpeg4_MASK            0x08000000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Mpeg4_SHIFT           27

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: VC_TTMbf [26:26] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VC_TTMbf_MASK         0x04000000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VC_TTMbf_SHIFT        26

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: VC_TTFrmSize [25:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VC_TTFrmSize_MASK     0x03000000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VC_TTFrmSize_SHIFT    24

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: reserved0 [23:22] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_reserved0_MASK        0x00c00000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_reserved0_SHIFT       22

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: VC_DBlkEna [21:21] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VC_DBlkEna_MASK       0x00200000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VC_DBlkEna_SHIFT      21

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: VC_OlapEna [20:20] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VC_OlapEna_MASK       0x00100000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VC_OlapEna_SHIFT      20

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: FastEna [19:19] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_FastEna_MASK          0x00080000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_FastEna_SHIFT         19

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: Skip [18:18] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Skip_MASK             0x00040000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Skip_SHIFT            18

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: Intra_264 [17:17] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Intra_264_MASK        0x00020000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Intra_264_SHIFT       17

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: Fetch_QP [16:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Fetch_QP_MASK         0x00010000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Fetch_QP_SHIFT        16

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: Type [15:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Type_MASK             0x0000c000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Type_SHIFT            14

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: SubType [13:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_SubType_MASK          0x00003000
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_SubType_SHIFT         12

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: SwapCBP [11:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_SwapCBP_MASK          0x00000800
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_SwapCBP_SHIFT         11

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: WrXNZero [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_WrXNZero_MASK         0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_WrXNZero_SHIFT        10

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: DCPrecision [09:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_DCPrecision_MASK      0x00000300
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_DCPrecision_SHIFT     8

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: VLCTable1 [07:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VLCTable1_MASK        0x00000080
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_VLCTable1_SHIFT       7

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: Intra [06:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Intra_MASK            0x00000040
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_Intra_SHIFT           6

/* DECODE_SINT_0 :: REG_SINT_DO_RESID :: CBP [05:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_CBP_MASK              0x0000003f
#define BCHP_DECODE_SINT_0_REG_SINT_DO_RESID_CBP_SHIFT             0

/***************************************************************************
 *REG_SINT_XNZERO - REG_SINT_XNZERO
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_XNZERO :: reserved0 [31:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_reserved0_MASK          0xffff0000
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_reserved0_SHIFT         16

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B15 [15:15] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B15_MASK                0x00008000
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B15_SHIFT               15

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B14 [14:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B14_MASK                0x00004000
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B14_SHIFT               14

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B13 [13:13] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B13_MASK                0x00002000
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B13_SHIFT               13

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B12 [12:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B12_MASK                0x00001000
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B12_SHIFT               12

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B11 [11:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B11_MASK                0x00000800
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B11_SHIFT               11

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B10 [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B10_MASK                0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B10_SHIFT               10

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B9 [09:09] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B9_MASK                 0x00000200
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B9_SHIFT                9

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B8 [08:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B8_MASK                 0x00000100
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B8_SHIFT                8

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B7 [07:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B7_MASK                 0x00000080
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B7_SHIFT                7

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B6 [06:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B6_MASK                 0x00000040
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B6_SHIFT                6

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B5 [05:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B5_MASK                 0x00000020
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B5_SHIFT                5

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B4 [04:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B4_MASK                 0x00000010
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B4_SHIFT                4

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B3 [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B3_MASK                 0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B3_SHIFT                3

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B2 [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B2_MASK                 0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B2_SHIFT                2

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B1 [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B1_MASK                 0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B1_SHIFT                1

/* DECODE_SINT_0 :: REG_SINT_XNZERO :: B0 [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B0_MASK                 0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_XNZERO_B0_SHIFT                0

/***************************************************************************
 *REG_SINT_VEC_MBTYPE - REG_SINT_VEC_MBTYPE
 ***************************************************************************/
/* union - case H264 [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: reserved0 [31:25] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_reserved0_MASK 0xfe000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_reserved0_SHIFT 25

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: SubMBType3 [24:21] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_SubMBType3_MASK 0x01e00000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_SubMBType3_SHIFT 21

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: reserved1 [20:20] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_reserved1_MASK 0x00100000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_reserved1_SHIFT 20

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: SubMBType2 [19:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_SubMBType2_MASK 0x000f0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_SubMBType2_SHIFT 16

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: reserved2 [15:15] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_reserved2_MASK 0x00008000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_reserved2_SHIFT 15

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: SubMBType1 [14:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_SubMBType1_MASK 0x00007800
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_SubMBType1_SHIFT 11

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: reserved3 [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_reserved3_MASK 0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_reserved3_SHIFT 10

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: SubMBType0 [09:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_SubMBType0_MASK 0x000003c0
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_SubMBType0_SHIFT 6

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: MBType [05:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_MBType_MASK    0x0000003e
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_MBType_SHIFT   1

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: H264 :: ISB [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_ISB_MASK       0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_H264_ISB_SHIFT      0

/* union - case VC1 [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: reserved0 [31:22] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_reserved0_MASK  0xffc00000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_reserved0_SHIFT 22

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: BlkPat [21:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_BlkPat_MASK     0x003f0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_BlkPat_SHIFT    16

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: reserved1 [15:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_reserved1_MASK  0x0000c000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_reserved1_SHIFT 14

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: MBMode [13:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_MBMode_MASK     0x00003f00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_MBMode_SHIFT    8

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: reserved2 [07:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_reserved2_MASK  0x00000080
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_reserved2_SHIFT 7

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: BMVType [06:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_BMVType_MASK    0x00000060
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_BMVType_SHIFT   5

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: MVSW [04:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_MVSW_MASK       0x00000010
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_MVSW_SHIFT      4

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: InterpMVP [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_InterpMVP_MASK  0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_InterpMVP_SHIFT 3

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: Forward [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_Forward_MASK    0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_Forward_SHIFT   2

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: Direct [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_Direct_MASK     0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_Direct_SHIFT    1

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: VC1 :: Skip [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_Skip_MASK       0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_VC1_Skip_SHIFT      0

/* union - case MPEG4 [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: reserved0 [31:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_reserved0_MASK 0xffffc000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_reserved0_SHIFT 14

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: qpel [13:13] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_qpel_MASK     0x00002000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_qpel_SHIFT    13

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: gmc [12:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_gmc_MASK      0x00001000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_gmc_SHIFT     12

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: no_mvd [11:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_no_mvd_MASK   0x00000800
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_no_mvd_SHIFT  11

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: intra [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_intra_MASK    0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_intra_SHIFT   10

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: fcode_back [09:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_fcode_back_MASK 0x00000380
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_fcode_back_SHIFT 7

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: fcode_fwd [06:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_fcode_fwd_MASK 0x00000070
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_fcode_fwd_SHIFT 4

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: four_mv [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_four_mv_MASK  0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_four_mv_SHIFT 3

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: alt_mv [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_alt_mv_MASK   0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_alt_mv_SHIFT  2

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: direct [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_direct_MASK   0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_direct_SHIFT  1

/* DECODE_SINT_0 :: REG_SINT_VEC_MBTYPE :: MPEG4 :: skip [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_skip_MASK     0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MBTYPE_MPEG4_skip_SHIFT    0

/***************************************************************************
 *REG_SINT_VEC_RESID - REG_SINT_VEC_RESID
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_RESID :: Y_Residual [31:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_RESID_Y_Residual_MASK      0xffff0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_RESID_Y_Residual_SHIFT     16

/* DECODE_SINT_0 :: REG_SINT_VEC_RESID :: X_Residual [15:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_RESID_X_Residual_MASK      0x0000ffff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_RESID_X_Residual_SHIFT     0

/***************************************************************************
 *REG_SINT_VEC_DMODE - REG_SINT_VEC_DMODE
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_DMODE :: reserved0 [31:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DMODE_reserved0_MASK       0xfffffff0
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DMODE_reserved0_SHIFT      4

/* DECODE_SINT_0 :: REG_SINT_VEC_DMODE :: Dmode [03:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DMODE_Dmode_MASK           0x0000000f
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DMODE_Dmode_SHIFT          0

/***************************************************************************
 *REG_SINT_VEC_TOP_LD - REG_SINT_VEC_TOP_LD
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_TOP_LD :: reserved0 [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOP_LD_reserved0_MASK      0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOP_LD_reserved0_SHIFT     0

/***************************************************************************
 *REG_SINT_VEC_DO_CONST - REG_SINT_VEC_DO_CONST
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: reserved0 [31:28] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_reserved0_MASK    0xf0000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_reserved0_SHIFT   28

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: direct_frm2fld [27:27] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_direct_frm2fld_MASK 0x08000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_direct_frm2fld_SHIFT 27

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: wholepel_8x8 [26:26] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_wholepel_8x8_MASK 0x04000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_wholepel_8x8_SHIFT 26

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: wholepel_all [25:25] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_wholepel_all_MASK 0x02000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_wholepel_all_SHIFT 25

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: VC1_1ref_is_bot [24:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_1ref_is_bot_MASK 0x01000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_1ref_is_bot_SHIFT 24

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: refdist_back [23:22] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_refdist_back_MASK 0x00c00000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_refdist_back_SHIFT 22

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: refdist_fwd [21:20] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_refdist_fwd_MASK  0x00300000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_refdist_fwd_SHIFT 20

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: VC1_2nd_fld [19:19] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_2nd_fld_MASK  0x00080000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_2nd_fld_SHIFT 19

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: Back_is_intl [18:18] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Back_is_intl_MASK 0x00040000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Back_is_intl_SHIFT 18

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: Fwd_is_intl [17:17] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Fwd_is_intl_MASK  0x00020000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Fwd_is_intl_SHIFT 17

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: VC1_2ref [16:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_2ref_MASK     0x00010000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_2ref_SHIFT    16

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: VC1_bfract_gt_half [15:15] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_bfract_gt_half_MASK 0x00008000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_bfract_gt_half_SHIFT 15

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: VC1_DmvRange [14:13] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_DmvRange_MASK 0x00006000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_DmvRange_SHIFT 13

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: VC1_mvRange [12:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_mvRange_MASK  0x00001800
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_mvRange_SHIFT 11

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: VC1_HalfPel [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_HalfPel_MASK  0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_VC1_HalfPel_SHIFT 10

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: MVDiff [09:09] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_MVDiff_MASK       0x00000200
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_MVDiff_SHIFT      9

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: ROLT [08:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_ROLT_MASK         0x00000100
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_ROLT_SHIFT        8

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: Lcpy [07:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Lcpy_MASK         0x00000080
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Lcpy_SHIFT        7

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: reserved1 [06:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_reserved1_MASK    0x00000040
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_reserved1_SHIFT   6

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: Pskip [05:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Pskip_MASK        0x00000020
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Pskip_SHIFT       5

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: Intra [04:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Intra_MASK        0x00000010
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_Intra_SHIFT       4

/* DECODE_SINT_0 :: REG_SINT_VEC_DO_CONST :: reserved2 [03:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_reserved2_MASK    0x0000000f
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_DO_CONST_reserved2_SHIFT   0

/***************************************************************************
 *REG_SINT_VEC_MVDIFF - Deblocking Motion Vector Difference
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V15 [31:31] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V15_MASK            0x80000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V15_SHIFT           31

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V14 [30:30] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V14_MASK            0x40000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V14_SHIFT           30

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V13 [29:29] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V13_MASK            0x20000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V13_SHIFT           29

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V12 [28:28] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V12_MASK            0x10000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V12_SHIFT           28

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V11 [27:27] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V11_MASK            0x08000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V11_SHIFT           27

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V10 [26:26] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V10_MASK            0x04000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V10_SHIFT           26

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V9 [25:25] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V9_MASK             0x02000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V9_SHIFT            25

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V8 [24:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V8_MASK             0x01000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V8_SHIFT            24

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V7 [23:23] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V7_MASK             0x00800000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V7_SHIFT            23

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V6 [22:22] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V6_MASK             0x00400000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V6_SHIFT            22

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V5 [21:21] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V5_MASK             0x00200000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V5_SHIFT            21

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V4 [20:20] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V4_MASK             0x00100000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V4_SHIFT            20

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V3 [19:19] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V3_MASK             0x00080000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V3_SHIFT            19

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V2 [18:18] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V2_MASK             0x00040000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V2_SHIFT            18

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V1 [17:17] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V1_MASK             0x00020000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V1_SHIFT            17

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: V0 [16:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V0_MASK             0x00010000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_V0_SHIFT            16

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H15 [15:15] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H15_MASK            0x00008000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H15_SHIFT           15

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H14 [14:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H14_MASK            0x00004000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H14_SHIFT           14

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H13 [13:13] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H13_MASK            0x00002000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H13_SHIFT           13

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H12 [12:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H12_MASK            0x00001000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H12_SHIFT           12

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H11 [11:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H11_MASK            0x00000800
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H11_SHIFT           11

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H10 [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H10_MASK            0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H10_SHIFT           10

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H9 [09:09] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H9_MASK             0x00000200
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H9_SHIFT            9

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H8 [08:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H8_MASK             0x00000100
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H8_SHIFT            8

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H7 [07:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H7_MASK             0x00000080
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H7_SHIFT            7

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H6 [06:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H6_MASK             0x00000040
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H6_SHIFT            6

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H5 [05:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H5_MASK             0x00000020
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H5_SHIFT            5

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H4 [04:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H4_MASK             0x00000010
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H4_SHIFT            4

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H3 [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H3_MASK             0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H3_SHIFT            3

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H2 [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H2_MASK             0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H2_SHIFT            2

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H1 [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H1_MASK             0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H1_SHIFT            1

/* DECODE_SINT_0 :: REG_SINT_VEC_MVDIFF :: H0 [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H0_MASK             0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVDIFF_H0_SHIFT            0

/***************************************************************************
 *REG_SINT_VEC_REFIDX - REG_SINT_VEC_REFIDX
 ***************************************************************************/
/* union - case WRITE [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: WRITE :: reserved0 [31:30] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_reserved0_MASK 0xc0000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_reserved0_SHIFT 30

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: WRITE :: RefIdx3 [29:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_RefIdx3_MASK  0x3f000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_RefIdx3_SHIFT 24

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: WRITE :: reserved1 [23:22] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_reserved1_MASK 0x00c00000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_reserved1_SHIFT 22

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: WRITE :: RefIdx2 [21:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_RefIdx2_MASK  0x003f0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_RefIdx2_SHIFT 16

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: WRITE :: reserved2 [15:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_reserved2_MASK 0x0000c000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_reserved2_SHIFT 14

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: WRITE :: RefIdx1 [13:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_RefIdx1_MASK  0x00003f00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_RefIdx1_SHIFT 8

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: WRITE :: reserved3 [07:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_reserved3_MASK 0x000000c0
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_reserved3_SHIFT 6

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: WRITE :: RefIdx0 [05:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_RefIdx0_MASK  0x0000003f
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_WRITE_RefIdx0_SHIFT 0

/* union - case READ [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: READ :: reserved0 [31:30] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_reserved0_MASK 0xc0000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_reserved0_SHIFT 30

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: READ :: Ref1_L1 [29:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_Ref1_L1_MASK   0x3f000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_Ref1_L1_SHIFT  24

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: READ :: reserved1 [23:22] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_reserved1_MASK 0x00c00000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_reserved1_SHIFT 22

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: READ :: Ref1_L0 [21:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_Ref1_L0_MASK   0x003f0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_Ref1_L0_SHIFT  16

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: READ :: reserved2 [15:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_reserved2_MASK 0x0000c000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_reserved2_SHIFT 14

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: READ :: Ref0_L1 [13:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_Ref0_L1_MASK   0x00003f00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_Ref0_L1_SHIFT  8

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: READ :: reserved3 [07:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_reserved3_MASK 0x000000c0
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_reserved3_SHIFT 6

/* DECODE_SINT_0 :: REG_SINT_VEC_REFIDX :: READ :: Ref0_L0 [05:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_Ref0_L0_MASK   0x0000003f
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFIDX_READ_Ref0_L0_SHIFT  0

/***************************************************************************
 *REG_SINT_VEC_TOPREF - REG_SINT_VEC_TOPREF
 ***************************************************************************/
/* union - case H264 [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: H264 :: L1RefB1 [31:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_H264_L1RefB1_MASK   0xff000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_H264_L1RefB1_SHIFT  24

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: H264 :: L1RefB0 [23:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_H264_L1RefB0_MASK   0x00ff0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_H264_L1RefB0_SHIFT  16

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: H264 :: L0RefB1 [15:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_H264_L0RefB1_MASK   0x0000ff00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_H264_L0RefB1_SHIFT  8

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: H264 :: L0RefB0 [07:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_H264_L0RefB0_MASK   0x000000ff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_H264_L0RefB0_SHIFT  0

/* union - case VC1 [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: ChrIntra [31:31] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_ChrIntra_MASK   0x80000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_ChrIntra_SHIFT  31

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: IsField [30:30] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_IsField_MASK    0x40000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_IsField_SHIFT   30

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: Blk3Bac [29:28] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk3Bac_MASK    0x30000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk3Bac_SHIFT   28

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: Blk2Bac [27:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk2Bac_MASK    0x0f000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk2Bac_SHIFT   24

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: Blk1Back [23:20] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk1Back_MASK   0x00f00000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk1Back_SHIFT  20

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: Blk0Back [19:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk0Back_MASK   0x000f0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk0Back_SHIFT  16

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: Blk3Fwd [15:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk3Fwd_MASK    0x0000f000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk3Fwd_SHIFT   12

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: Blk2Fwd [11:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk2Fwd_MASK    0x00000f00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk2Fwd_SHIFT   8

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: Blk1Fwd [07:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk1Fwd_MASK    0x000000f0
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk1Fwd_SHIFT   4

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPREF :: VC1 :: Blk0Fwd [03:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk0Fwd_MASK    0x0000000f
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPREF_VC1_Blk0Fwd_SHIFT   0

/***************************************************************************
 *REG_SINT_VEC_TOPTOPREF - REG_SINT_VEC_TOPTOPREF
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_TOPTOPREF :: L1PicB1 [31:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF_L1PicB1_MASK     0xff000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF_L1PicB1_SHIFT    24

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPTOPREF :: reserved0 [23:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF_reserved0_MASK   0x00ff0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF_reserved0_SHIFT  16

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPTOPREF :: L0PicB1 [15:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF_L0PicB1_MASK     0x0000ff00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF_L0PicB1_SHIFT    8

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPTOPREF :: reserved1 [07:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF_reserved1_MASK   0x000000ff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPTOPREF_reserved1_SHIFT  0

/***************************************************************************
 *REG_SINT_VEC_COL_TYPE - REG_SINT_VEC_COL_TYPE
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: MBAFF [31:31] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_MBAFF_MASK        0x80000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_MBAFF_SHIFT       31

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: TFld [30:30] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_TFld_MASK         0x40000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_TFld_SHIFT        30

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: Field [29:29] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Field_MASK        0x20000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Field_SHIFT       29

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: reserved0 [28:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_reserved0_MASK    0x1ffff000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_reserved0_SHIFT   12

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: AvsSpatial1 [11:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_AvsSpatial1_MASK  0x00000800
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_AvsSpatial1_SHIFT 11

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: AvsSpatial0 [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_AvsSpatial0_MASK  0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_AvsSpatial0_SHIFT 10

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: Sub3 [09:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Sub3_MASK         0x00000300
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Sub3_SHIFT        8

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: Sub2 [07:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Sub2_MASK         0x000000c0
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Sub2_SHIFT        6

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: Sub1 [05:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Sub1_MASK         0x00000030
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Sub1_SHIFT        4

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: Sub0 [03:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Sub0_MASK         0x0000000c
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Sub0_SHIFT        2

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_TYPE :: Type [01:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Type_MASK         0x00000003
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_TYPE_Type_SHIFT        0

/***************************************************************************
 *REG_SINT_VEC_COL_REFID - REG_SINT_VEC_COL_REFID
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_COL_REFID :: reserved0 [31:29] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_reserved0_MASK   0xe0000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_reserved0_SHIFT  29

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_REFID :: RefIdx3 [28:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_RefIdx3_MASK     0x1f000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_RefIdx3_SHIFT    24

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_REFID :: reserved1 [23:21] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_reserved1_MASK   0x00e00000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_reserved1_SHIFT  21

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_REFID :: RefIdx2 [20:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_RefIdx2_MASK     0x001f0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_RefIdx2_SHIFT    16

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_REFID :: reserved2 [15:13] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_reserved2_MASK   0x0000e000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_reserved2_SHIFT  13

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_REFID :: RefIdx1 [12:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_RefIdx1_MASK     0x00001f00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_RefIdx1_SHIFT    8

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_REFID :: reserved3 [07:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_reserved3_MASK   0x000000e0
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_reserved3_SHIFT  5

/* DECODE_SINT_0 :: REG_SINT_VEC_COL_REFID :: RefIdx0 [04:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_RefIdx0_MASK     0x0000001f
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COL_REFID_RefIdx0_SHIFT    0

/***************************************************************************
 *REG_SINT_VEC_TOPPIC - REG_SINT_VEC_TOPPIC
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_TOPPIC :: L1PicB1 [31:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC_L1PicB1_MASK        0xff000000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC_L1PicB1_SHIFT       24

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPPIC :: L1PicB0 [23:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC_L1PicB0_MASK        0x00ff0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC_L1PicB0_SHIFT       16

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPPIC :: L0PicB1 [15:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC_L0PicB1_MASK        0x0000ff00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC_L0PicB1_SHIFT       8

/* DECODE_SINT_0 :: REG_SINT_VEC_TOPPIC :: L0PicB0 [07:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC_L0PicB0_MASK        0x000000ff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_TOPPIC_L0PicB0_SHIFT       0

/***************************************************************************
 *REG_SINT_VEC_VC1_INFO - REG_SINT_VEC_VC1_INFO
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: reserved0 [31:22] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_reserved0_MASK    0xffc00000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_reserved0_SHIFT   22

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: Intra_Flags [21:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_Intra_Flags_MASK  0x003f0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_Intra_Flags_SHIFT 16

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: reserved1 [15:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_reserved1_MASK    0x0000c000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_reserved1_SHIFT   14

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: CBPCY [13:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_CBPCY_MASK        0x00003f00
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_CBPCY_SHIFT       8

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: reserved2 [07:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_reserved2_MASK    0x000000c0
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_reserved2_SHIFT   6

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: BMV_TYPE [05:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_BMV_TYPE_MASK     0x00000030
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_BMV_TYPE_SHIFT    4

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: field_4MV [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_field_4MV_MASK    0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_field_4MV_SHIFT   3

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: GET_AC_PRED [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_GET_AC_PRED_MASK  0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_GET_AC_PRED_SHIFT 2

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: COEFS_PRES [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_COEFS_PRES_MASK   0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_COEFS_PRES_SHIFT  1

/* DECODE_SINT_0 :: REG_SINT_VEC_VC1_INFO :: INTRA [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_INTRA_MASK        0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_VC1_INFO_INTRA_SHIFT       0

/***************************************************************************
 *REG_SINT_VEC_REFPIC - REG_SINT_VEC_REFPIC - H.264 only
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_REFPIC :: reserved0 [31:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC_reserved0_MASK      0xfffffff8
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC_reserved0_SHIFT     3

/* DECODE_SINT_0 :: REG_SINT_VEC_REFPIC :: Hwimpiwt [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC_Hwimpiwt_MASK       0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC_Hwimpiwt_SHIFT      2

/* DECODE_SINT_0 :: REG_SINT_VEC_REFPIC :: UserRev [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC_UserRev_MASK        0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC_UserRev_SHIFT       1

/* DECODE_SINT_0 :: REG_SINT_VEC_REFPIC :: RamSel [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC_RamSel_MASK         0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REFPIC_RamSel_SHIFT        0

/***************************************************************************
 *REG_SINT_VEC_COUNT - REG_SINT_VEC_COUNT
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_COUNT :: Cnt8x8UA [31:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COUNT_Cnt8x8UA_MASK        0xffff0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COUNT_Cnt8x8UA_SHIFT       16

/* DECODE_SINT_0 :: REG_SINT_VEC_COUNT :: Cnt8x8 [15:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COUNT_Cnt8x8_MASK          0x0000ffff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_COUNT_Cnt8x8_SHIFT         0

/***************************************************************************
 *REG_SINT_VEC_MVD_FIFO - REG_SINT_VEC_MVD_FIFO
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_MVD_FIFO :: Data [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVD_FIFO_Data_MASK         0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MVD_FIFO_Data_SHIFT        0

/***************************************************************************
 *REG_SINT_DIVX_TABSEL - REG_SINT_DIVX_TABSEL
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: reserved0 [31:09] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_reserved0_MASK     0xfffffe00
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_reserved0_SHIFT    9

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: P_frame [08:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_P_frame_MASK       0x00000100
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_P_frame_SHIFT      8

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: alt_I_AC_chrom_DCT [07:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_AC_chrom_DCT_MASK 0x00000080
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_AC_chrom_DCT_SHIFT 7

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: alt_I_AC_chrom_DCT_index [06:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_AC_chrom_DCT_index_MASK 0x00000040
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_AC_chrom_DCT_index_SHIFT 6

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: alt_I_AC_lum_DCT [05:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_AC_lum_DCT_MASK 0x00000020
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_AC_lum_DCT_SHIFT 5

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: alt_I_AC_lum_DCT_index [04:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_AC_lum_DCT_index_MASK 0x00000010
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_AC_lum_DCT_index_SHIFT 4

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: alt_I_DC_DCT [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_DC_DCT_MASK  0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_I_DC_DCT_SHIFT 3

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: alt_P_AC_DCT [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_P_AC_DCT_MASK  0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_P_AC_DCT_SHIFT 2

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: alt_P_AC_DCT_index [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_P_AC_DCT_index_MASK 0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_P_AC_DCT_index_SHIFT 1

/* DECODE_SINT_0 :: REG_SINT_DIVX_TABSEL :: alt_P_DC_DCT [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_P_DC_DCT_MASK  0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_DIVX_TABSEL_alt_P_DC_DCT_SHIFT 0

/***************************************************************************
 *REG_SINT_CTL_AUX - REG_SINT_CTL_AUX
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_CTL_AUX :: reserved0 [31:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_AUX_reserved0_MASK         0xfffffffc
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_AUX_reserved0_SHIFT        2

/* DECODE_SINT_0 :: REG_SINT_CTL_AUX :: ref_ld_2bit [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_AUX_ref_ld_2bit_MASK       0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_AUX_ref_ld_2bit_SHIFT      1

/* DECODE_SINT_0 :: REG_SINT_CTL_AUX :: avs_mode [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_AUX_avs_mode_MASK          0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_AUX_avs_mode_SHIFT         0

/***************************************************************************
 *REG_SINT_VEC_REGEND - REG_SINT_VEC_REGEND
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_REGEND :: reserved0 [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REGEND_reserved0_MASK      0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_REGEND_reserved0_SHIFT     0

/***************************************************************************
 *REG_SINT_CTL - REG_SINT_CTL
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_CTL :: VC1 [31:31] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_VC1_MASK                   0x80000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_VC1_SHIFT                  31

/* DECODE_SINT_0 :: REG_SINT_CTL :: regacc_disable [30:30] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_regacc_disable_MASK        0x40000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_regacc_disable_SHIFT       30

/* DECODE_SINT_0 :: REG_SINT_CTL :: use_qs_table [29:29] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_use_qs_table_MASK          0x20000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_use_qs_table_SHIFT         29

/* DECODE_SINT_0 :: REG_SINT_CTL :: MPEG4 [28:28] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_MPEG4_MASK                 0x10000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_MPEG4_SHIFT                28

/* DECODE_SINT_0 :: REG_SINT_CTL :: xform_8x8 [27:27] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_xform_8x8_MASK             0x08000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_xform_8x8_SHIFT            27

/* DECODE_SINT_0 :: REG_SINT_CTL :: mode_8x8 [26:26] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_mode_8x8_MASK              0x04000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_mode_8x8_SHIFT             26

/* DECODE_SINT_0 :: REG_SINT_CTL :: mono_mode [25:25] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_mono_mode_MASK             0x02000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_mono_mode_SHIFT            25

/* DECODE_SINT_0 :: REG_SINT_CTL :: DIVX311 [24:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_DIVX311_MASK               0x01000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_DIVX311_SHIFT              24

/* DECODE_SINT_0 :: REG_SINT_CTL :: Profile [23:22] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Profile_MASK               0x00c00000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Profile_SHIFT              22

/* DECODE_SINT_0 :: REG_SINT_CTL :: IWtPred [21:21] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_IWtPred_MASK               0x00200000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_IWtPred_SHIFT              21

/* DECODE_SINT_0 :: REG_SINT_CTL :: WtPred [20:20] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_WtPred_MASK                0x00100000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_WtPred_SHIFT               20

/* DECODE_SINT_0 :: REG_SINT_CTL :: Use_field_pred [19:19] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Use_field_pred_MASK        0x00080000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Use_field_pred_SHIFT       19

/* DECODE_SINT_0 :: REG_SINT_CTL :: bot_field [18:18] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_bot_field_MASK             0x00040000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_bot_field_SHIFT            18

/* DECODE_SINT_0 :: REG_SINT_CTL :: L1_Eq_2 [17:17] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_L1_Eq_2_MASK               0x00020000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_L1_Eq_2_SHIFT              17

/* DECODE_SINT_0 :: REG_SINT_CTL :: L1_Eq_1 [16:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_L1_Eq_1_MASK               0x00010000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_L1_Eq_1_SHIFT              16

/* DECODE_SINT_0 :: REG_SINT_CTL :: L0_Eq_2 [15:15] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_L0_Eq_2_MASK               0x00008000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_L0_Eq_2_SHIFT              15

/* DECODE_SINT_0 :: REG_SINT_CTL :: L0_Eq_1 [14:14] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_L0_Eq_1_MASK               0x00004000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_L0_Eq_1_SHIFT              14

/* DECODE_SINT_0 :: REG_SINT_CTL :: new_slice [13:13] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_new_slice_MASK             0x00002000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_new_slice_SHIFT            13

/* DECODE_SINT_0 :: REG_SINT_CTL :: reserved_for_eco0 [12:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_reserved_for_eco0_MASK     0x00001000
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_reserved_for_eco0_SHIFT    12

/* DECODE_SINT_0 :: REG_SINT_CTL :: Dir_8x8 [11:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Dir_8x8_MASK               0x00000800
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Dir_8x8_SHIFT              11

/* DECODE_SINT_0 :: REG_SINT_CTL :: Spa_Dir [10:10] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Spa_Dir_MASK               0x00000400
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Spa_Dir_SHIFT              10

/* DECODE_SINT_0 :: REG_SINT_CTL :: PTYPE [09:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_PTYPE_MASK                 0x00000300
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_PTYPE_SHIFT                8

/* DECODE_SINT_0 :: REG_SINT_CTL :: MBAFF [07:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_MBAFF_MASK                 0x00000080
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_MBAFF_SHIFT                7

/* DECODE_SINT_0 :: REG_SINT_CTL :: TFld [06:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_TFld_MASK                  0x00000040
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_TFld_SHIFT                 6

/* DECODE_SINT_0 :: REG_SINT_CTL :: Field [05:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Field_MASK                 0x00000020
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Field_SHIFT                5

/* DECODE_SINT_0 :: REG_SINT_CTL :: CAVLC [04:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_CAVLC_MASK                 0x00000010
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_CAVLC_SHIFT                4

/* DECODE_SINT_0 :: REG_SINT_CTL :: Uleft [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Uleft_MASK                 0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Uleft_SHIFT                3

/* DECODE_SINT_0 :: REG_SINT_CTL :: Top [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Top_MASK                   0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Top_SHIFT                  2

/* DECODE_SINT_0 :: REG_SINT_CTL :: Left [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Left_MASK                  0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_Left_SHIFT                 1

/* DECODE_SINT_0 :: REG_SINT_CTL :: URtAvail [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_URtAvail_MASK              0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_CTL_URtAvail_SHIFT             0

/***************************************************************************
 *REG_SINT_VLC_TOPCTX - REG_SINT_VLC_TOPCTX
 ***************************************************************************/
/* union - case VLC [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VLC :: V2 [31:28] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_V2_MASK         0xf0000000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_V2_SHIFT        28

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VLC :: V3 [27:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_V3_MASK         0x0f000000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_V3_SHIFT        24

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VLC :: U2 [23:20] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_U2_MASK         0x00f00000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_U2_SHIFT        20

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VLC :: U3 [19:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_U3_MASK         0x000f0000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_U3_SHIFT        16

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VLC :: Lum10 [15:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_Lum10_MASK      0x0000f000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_Lum10_SHIFT     12

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VLC :: Lum11 [11:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_Lum11_MASK      0x00000f00
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_Lum11_SHIFT     8

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VLC :: Lum14 [07:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_Lum14_MASK      0x000000f0
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_Lum14_SHIFT     4

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VLC :: Lum15 [03:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_Lum15_MASK      0x0000000f
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VLC_Lum15_SHIFT     0

/* union - case VC1 [31:00] */
/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VC1 :: reserved0 [31:25] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_reserved0_MASK  0xfe000000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_reserved0_SHIFT 25

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VC1 :: Top4x4 [24:21] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_Top4x4_MASK     0x01e00000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_Top4x4_SHIFT    21

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VC1 :: TopXNZ [20:13] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_TopXNZ_MASK     0x001fe000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_TopXNZ_SHIFT    13

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VC1 :: TopOlapEnb [12:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_TopOlapEnb_MASK 0x00001000
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_TopOlapEnb_SHIFT 12

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VC1 :: TopIntra [11:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_TopIntra_MASK   0x00000fc0
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_TopIntra_SHIFT  6

/* DECODE_SINT_0 :: REG_SINT_VLC_TOPCTX :: VC1 :: TopCBP [05:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_TopCBP_MASK     0x0000003f
#define BCHP_DECODE_SINT_0_REG_SINT_VLC_TOPCTX_VC1_TopCBP_SHIFT    0

/***************************************************************************
 *REG_SINT_SLICE_ID - REG_SINT_SLICE_ID
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_SLICE_ID :: reserved0 [31:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_SLICE_ID_reserved0_MASK        0xfffff000
#define BCHP_DECODE_SINT_0_REG_SINT_SLICE_ID_reserved0_SHIFT       12

/* DECODE_SINT_0 :: REG_SINT_SLICE_ID :: SliceID [11:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_SLICE_ID_SliceID_MASK          0x00000fff
#define BCHP_DECODE_SINT_0_REG_SINT_SLICE_ID_SliceID_SHIFT         0

/***************************************************************************
 *REG_SINT_QP - REG_SINT_QP
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_QP :: reserved0 [31:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_QP_reserved0_MASK              0xffffffc0
#define BCHP_DECODE_SINT_0_REG_SINT_QP_reserved0_SHIFT             6

/* DECODE_SINT_0 :: REG_SINT_QP :: qp [05:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_QP_qp_MASK                     0x0000003f
#define BCHP_DECODE_SINT_0_REG_SINT_QP_qp_SHIFT                    0

/***************************************************************************
 *REG_SINT_TOP_BASE_ADDR - REG_SINT_TOP_BASE_ADDR
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_TOP_BASE_ADDR :: Addr [31:06] */
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_BASE_ADDR_Addr_MASK        0xffffffc0
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_BASE_ADDR_Addr_SHIFT       6

/* DECODE_SINT_0 :: REG_SINT_TOP_BASE_ADDR :: reserved0 [05:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_BASE_ADDR_reserved0_MASK   0x0000003f
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_BASE_ADDR_reserved0_SHIFT  0

/***************************************************************************
 *REG_SINT_DIRCTX_WR_ADDR - REG_SINT_DIRCTX_WR_ADDR
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_DIRCTX_WR_ADDR :: Addr [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_DIRCTX_WR_ADDR_Addr_MASK       0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_DIRCTX_WR_ADDR_Addr_SHIFT      0

/***************************************************************************
 *REG_SINT_TOPCTX_DATA - REG_SINT_TOPCTX_DATA
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_TOPCTX_DATA :: Data [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_TOPCTX_DATA_Data_MASK          0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_TOPCTX_DATA_Data_SHIFT         0

/***************************************************************************
 *REG_SINT_XFER_SYMB - REG_SINT_XFER_SYMB
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_XFER_SYMB :: reserved0 [31:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_XFER_SYMB_reserved0_MASK       0xffff0000
#define BCHP_DECODE_SINT_0_REG_SINT_XFER_SYMB_reserved0_SHIFT      16

/* DECODE_SINT_0 :: REG_SINT_XFER_SYMB :: Type [15:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_XFER_SYMB_Type_MASK            0x0000ff00
#define BCHP_DECODE_SINT_0_REG_SINT_XFER_SYMB_Type_SHIFT           8

/* DECODE_SINT_0 :: REG_SINT_XFER_SYMB :: N [07:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_XFER_SYMB_N_MASK               0x000000ff
#define BCHP_DECODE_SINT_0_REG_SINT_XFER_SYMB_N_SHIFT              0

/***************************************************************************
 *REG_SINT_SMODE_BASE - REG_SINT_SMODE_BASE
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_SMODE_BASE :: Mode0 [31:28] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode0_MASK          0xf0000000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode0_SHIFT         28

/* DECODE_SINT_0 :: REG_SINT_SMODE_BASE :: Mode1 [27:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode1_MASK          0x0f000000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode1_SHIFT         24

/* DECODE_SINT_0 :: REG_SINT_SMODE_BASE :: Mode2 [23:20] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode2_MASK          0x00f00000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode2_SHIFT         20

/* DECODE_SINT_0 :: REG_SINT_SMODE_BASE :: Mode3 [19:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode3_MASK          0x000f0000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode3_SHIFT         16

/* DECODE_SINT_0 :: REG_SINT_SMODE_BASE :: Mode4 [15:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode4_MASK          0x0000f000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode4_SHIFT         12

/* DECODE_SINT_0 :: REG_SINT_SMODE_BASE :: Mode5 [11:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode5_MASK          0x00000f00
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode5_SHIFT         8

/* DECODE_SINT_0 :: REG_SINT_SMODE_BASE :: Mode6 [07:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode6_MASK          0x000000f0
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode6_SHIFT         4

/* DECODE_SINT_0 :: REG_SINT_SMODE_BASE :: Mode7 [03:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode7_MASK          0x0000000f
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_BASE_Mode7_SHIFT         0

/***************************************************************************
 *REG_SINT_SMODE_LEFT - REG_SINT_SMODE_LEFT
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_SMODE_LEFT :: reserved0 [31:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_reserved0_MASK      0xffff0000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_reserved0_SHIFT     16

/* DECODE_SINT_0 :: REG_SINT_SMODE_LEFT :: LeftMode5 [15:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_LeftMode5_MASK      0x0000f000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_LeftMode5_SHIFT     12

/* DECODE_SINT_0 :: REG_SINT_SMODE_LEFT :: LeftMode7 [11:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_LeftMode7_MASK      0x00000f00
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_LeftMode7_SHIFT     8

/* DECODE_SINT_0 :: REG_SINT_SMODE_LEFT :: LeftMode13 [07:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_LeftMode13_MASK     0x000000f0
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_LeftMode13_SHIFT    4

/* DECODE_SINT_0 :: REG_SINT_SMODE_LEFT :: LeftMode15 [03:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_LeftMode15_MASK     0x0000000f
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_LEFT_LeftMode15_SHIFT    0

/***************************************************************************
 *REG_SINT_SMODE_TOP - REG_SINT_SMODE_TOP
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_SMODE_TOP :: reserved0 [31:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_reserved0_MASK       0xffff0000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_reserved0_SHIFT      16

/* DECODE_SINT_0 :: REG_SINT_SMODE_TOP :: TopMode10 [15:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_TopMode10_MASK       0x0000f000
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_TopMode10_SHIFT      12

/* DECODE_SINT_0 :: REG_SINT_SMODE_TOP :: TopMode11 [11:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_TopMode11_MASK       0x00000f00
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_TopMode11_SHIFT      8

/* DECODE_SINT_0 :: REG_SINT_SMODE_TOP :: TopMode14 [07:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_TopMode14_MASK       0x000000f0
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_TopMode14_SHIFT      4

/* DECODE_SINT_0 :: REG_SINT_SMODE_TOP :: TopMode15 [03:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_TopMode15_MASK       0x0000000f
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_TOP_TopMode15_SHIFT      0

/***************************************************************************
 *REG_SINT_SMODE_END - REG_SINT_SMODE_END
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_SMODE_END :: reserved0 [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_END_reserved0_MASK       0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_SMODE_END_reserved0_SHIFT      0

/***************************************************************************
 *REG_SINT_CTX_INIT - REG_SINT_CTX_INIT
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_CTX_INIT :: reserved0 [31:25] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_reserved0_MASK        0xfe000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_reserved0_SHIFT       25

/* DECODE_SINT_0 :: REG_SINT_CTX_INIT :: MBAFF [24:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_MBAFF_MASK            0x01000000
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_MBAFF_SHIFT           24

/* DECODE_SINT_0 :: REG_SINT_CTX_INIT :: MBWIDTH [23:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_MBWIDTH_MASK          0x00ff0000
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_MBWIDTH_SHIFT         16

/* DECODE_SINT_0 :: REG_SINT_CTX_INIT :: YPOS [15:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_YPOS_MASK             0x0000ff00
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_YPOS_SHIFT            8

/* DECODE_SINT_0 :: REG_SINT_CTX_INIT :: XPOS [07:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_XPOS_MASK             0x000000ff
#define BCHP_DECODE_SINT_0_REG_SINT_CTX_INIT_XPOS_SHIFT            0

/***************************************************************************
 *REG_SINT_TOP_CTX - REG_SINT_TOP_CTX
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_TOP_CTX :: reserved0 [31:05] */
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_CTX_reserved0_MASK         0xffffffe0
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_CTX_reserved0_SHIFT        5

/* DECODE_SINT_0 :: REG_SINT_TOP_CTX :: TOP_TOP [04:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_CTX_TOP_TOP_MASK           0x00000010
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_CTX_TOP_TOP_SHIFT          4

/* DECODE_SINT_0 :: REG_SINT_TOP_CTX :: RD_OFFSET [03:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_CTX_RD_OFFSET_MASK         0x0000000f
#define BCHP_DECODE_SINT_0_REG_SINT_TOP_CTX_RD_OFFSET_SHIFT        0

/***************************************************************************
 *REG_SINT_VC1_TABSEL - REG_SINT_VC1_TABSEL
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: reserved0 [31:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_reserved0_MASK      0xff000000
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_reserved0_SHIFT     24

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: ESC_LVL_SZ [23:23] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_ESC_LVL_SZ_MASK     0x00800000
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_ESC_LVL_SZ_SHIFT    23

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: TTYPE [22:21] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_TTYPE_MASK          0x00600000
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_TTYPE_SHIFT         21

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: INTER_AC [20:19] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_INTER_AC_MASK       0x00180000
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_INTER_AC_SHIFT      19

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: Y_INTRA_AC [18:17] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_Y_INTRA_AC_MASK     0x00060000
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_Y_INTRA_AC_SHIFT    17

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: DCTABLE [16:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_DCTABLE_MASK        0x00010000
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_DCTABLE_SHIFT       16

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: reserved_for_eco1 [15:15] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_reserved_for_eco1_MASK 0x00008000
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_reserved_for_eco1_SHIFT 15

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: MBMODE [14:12] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_MBMODE_MASK         0x00007000
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_MBMODE_SHIFT        12

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: field_2REF [11:11] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_field_2REF_MASK     0x00000800
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_field_2REF_SHIFT    11

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: reserved_for_eco2 [10:07] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_reserved_for_eco2_MASK 0x00000780
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_reserved_for_eco2_SHIFT 7

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: CPPCY [06:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_CPPCY_MASK          0x00000070
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_CPPCY_SHIFT         4

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: field_2MB_PAT [03:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_field_2MB_PAT_MASK  0x0000000c
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_field_2MB_PAT_SHIFT 2

/* DECODE_SINT_0 :: REG_SINT_VC1_TABSEL :: field_4MB_PAT [01:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_field_4MB_PAT_MASK  0x00000003
#define BCHP_DECODE_SINT_0_REG_SINT_VC1_TABSEL_field_4MB_PAT_SHIFT 0

/***************************************************************************
 *REG_SINT_CNST_INTRA - REG_SINT_CNST_INTRA
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_CNST_INTRA :: reserved0 [31:04] */
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_reserved0_MASK      0xfffffff0
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_reserved0_SHIFT     4

/* DECODE_SINT_0 :: REG_SINT_CNST_INTRA :: ULftAvail [03:03] */
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_ULftAvail_MASK      0x00000008
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_ULftAvail_SHIFT     3

/* DECODE_SINT_0 :: REG_SINT_CNST_INTRA :: TopAvail [02:02] */
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_TopAvail_MASK       0x00000004
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_TopAvail_SHIFT      2

/* DECODE_SINT_0 :: REG_SINT_CNST_INTRA :: LeftAvail [01:01] */
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_LeftAvail_MASK      0x00000002
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_LeftAvail_SHIFT     1

/* DECODE_SINT_0 :: REG_SINT_CNST_INTRA :: URtAvail [00:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_URtAvail_MASK       0x00000001
#define BCHP_DECODE_SINT_0_REG_SINT_CNST_INTRA_URtAvail_SHIFT      0

/***************************************************************************
 *REG_SINT_OPIC_MEM_BASE - Outpic Lookup
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_OPIC_MEM_BASE :: OutPic3 [31:24] */
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE_OutPic3_MASK     0xff000000
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE_OutPic3_SHIFT    24

/* DECODE_SINT_0 :: REG_SINT_OPIC_MEM_BASE :: OutPic2 [23:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE_OutPic2_MASK     0x00ff0000
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE_OutPic2_SHIFT    16

/* DECODE_SINT_0 :: REG_SINT_OPIC_MEM_BASE :: OutPic1 [15:08] */
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE_OutPic1_MASK     0x0000ff00
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE_OutPic1_SHIFT    8

/* DECODE_SINT_0 :: REG_SINT_OPIC_MEM_BASE :: OutPic0 [07:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE_OutPic0_MASK     0x000000ff
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_BASE_OutPic0_SHIFT    0

/***************************************************************************
 *REG_SINT_OPIC_MEM_END - REG_SINT_OPIC_MEM_END
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_OPIC_MEM_END :: reserved0 [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_END_reserved0_MASK    0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_OPIC_MEM_END_reserved0_SHIFT   0

/***************************************************************************
 *REG_SINT_VEC_MEM_BASE - Vector Memory
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_MEM_BASE :: Vector_Y_Delta [31:16] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MEM_BASE_Vector_Y_Delta_MASK 0xffff0000
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MEM_BASE_Vector_Y_Delta_SHIFT 16

/* DECODE_SINT_0 :: REG_SINT_VEC_MEM_BASE :: Vector_X_Delta [15:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MEM_BASE_Vector_X_Delta_MASK 0x0000ffff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MEM_BASE_Vector_X_Delta_SHIFT 0

/***************************************************************************
 *REG_SINT_VEC_MEM_END - REG_SINT_VEC_MEM_END
 ***************************************************************************/
/* DECODE_SINT_0 :: REG_SINT_VEC_MEM_END :: reserved0 [31:00] */
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MEM_END_reserved0_MASK     0xffffffff
#define BCHP_DECODE_SINT_0_REG_SINT_VEC_MEM_END_reserved0_SHIFT    0

#endif /* #ifndef BCHP_DECODE_SINT_0_H__ */

/* End of File */
