/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 **********************************************************************
 * This file is part of the crystalhd device driver.
 *
 * This driver is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * This driver is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this driver.  If not, see <http://www.gnu.org/licenses/>.
 **********************************************************************
 *
 * $brcm_Workfile: bchp_decode_cpudmem_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 7/17/09 8:01p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jul 17 19:43:12 2009
 *                 MD5 Checksum         2914699efc3fb3edefca5cb4f4f38b34
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/70015/rdb/a0/bchp_decode_cpudmem_0.h $
 * 
 * Hydra_Software_Devel/1   7/17/09 8:01p albertl
 * PR56880: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_DECODE_CPUDMEM_0_H__
#define BCHP_DECODE_CPUDMEM_0_H__

/***************************************************************************
 *DECODE_CPUDMEM_0
 ***************************************************************************/
#define BCHP_DECODE_CPUDMEM_0_CPUDMEM_REG        0x00848000 /* CPUDMEM_REG */
#define BCHP_DECODE_CPUDMEM_0_CPUDMEM_END        0x0084fffc /* CPUDMEM_END */

/***************************************************************************
 *CPUDMEM_REG - CPUDMEM_REG
 ***************************************************************************/
/* DECODE_CPUDMEM_0 :: CPUDMEM_REG :: Addr [31:00] */
#define BCHP_DECODE_CPUDMEM_0_CPUDMEM_REG_Addr_MASK                0xffffffff
#define BCHP_DECODE_CPUDMEM_0_CPUDMEM_REG_Addr_SHIFT               0

/***************************************************************************
 *CPUDMEM_END - CPUDMEM_END
 ***************************************************************************/
/* DECODE_CPUDMEM_0 :: CPUDMEM_END :: reserved0 [31:00] */
#define BCHP_DECODE_CPUDMEM_0_CPUDMEM_END_reserved0_MASK           0xffffffff
#define BCHP_DECODE_CPUDMEM_0_CPUDMEM_END_reserved0_SHIFT          0

#endif /* #ifndef BCHP_DECODE_CPUDMEM_0_H__ */

/* End of File */
