/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 **********************************************************************
 * This file is part of the crystalhd device driver.
 *
 * This driver is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * This driver is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this driver.  If not, see <http://www.gnu.org/licenses/>.
 **********************************************************************
 *
 * $brcm_Workfile: bchp_mmscram.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 7/17/09 8:12p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jul 17 19:42:09 2009
 *                 MD5 Checksum         2914699efc3fb3edefca5cb4f4f38b34
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/70015/rdb/a0/bchp_mmscram.h $
 * 
 * Hydra_Software_Devel/1   7/17/09 8:12p albertl
 * PR56880: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_MMSCRAM_H__
#define BCHP_MMSCRAM_H__

/***************************************************************************
 *MMSCRAM - MMSCRAM Registers
 ***************************************************************************/
#define BCHP_MMSCRAM_RSV_S                       0x000fd000 /* RESERVED */
#define BCHP_MMSCRAM_RSV_E                       0x000feffc /* RESERVED */

/***************************************************************************
 *RSV_S - RESERVED
 ***************************************************************************/
/* MMSCRAM :: RSV_S :: reserved0 [31:00] */
#define BCHP_MMSCRAM_RSV_S_reserved0_MASK                          0xffffffff
#define BCHP_MMSCRAM_RSV_S_reserved0_SHIFT                         0

/***************************************************************************
 *RSV_E - RESERVED
 ***************************************************************************/
/* MMSCRAM :: RSV_E :: reserved0 [31:00] */
#define BCHP_MMSCRAM_RSV_E_reserved0_MASK                          0xffffffff
#define BCHP_MMSCRAM_RSV_E_reserved0_SHIFT                         0

#endif /* #ifndef BCHP_MMSCRAM_H__ */

/* End of File */
