/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_vich_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 7/17/09 8:22p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jul 17 19:43:22 2009
 *                 MD5 Checksum         2914699efc3fb3edefca5cb4f4f38b34
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/70015/rdb/a0/bchp_vich_0.h $
 * 
 * Hydra_Software_Devel/1   7/17/09 8:22p albertl
 * PR56880: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_VICH_0_H__
#define BCHP_VICH_0_H__

/***************************************************************************
 *VICH_0
 ***************************************************************************/
#define BCHP_VICH_0_RESERVED                     0x00b00000 /* RESERVED */
#define BCHP_VICH_0_RESERVED_END                 0x00b0004c /* RESERVED_END */

/***************************************************************************
 *RESERVED - RESERVED
 ***************************************************************************/
/* VICH_0 :: RESERVED :: reserved0 [31:00] */
#define BCHP_VICH_0_RESERVED_reserved0_MASK                        0xffffffff
#define BCHP_VICH_0_RESERVED_reserved0_SHIFT                       0

/***************************************************************************
 *RESERVED_END - RESERVED_END
 ***************************************************************************/
/* VICH_0 :: RESERVED_END :: reserved0 [31:00] */
#define BCHP_VICH_0_RESERVED_END_reserved0_MASK                    0xffffffff
#define BCHP_VICH_0_RESERVED_END_reserved0_SHIFT                   0

#endif /* #ifndef BCHP_VICH_0_H__ */

/* End of File */
