/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 **********************************************************************
 * This file is part of the crystalhd device driver.
 *
 * This driver is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * This driver is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this driver.  If not, see <http://www.gnu.org/licenses/>.
 **********************************************************************
 *
 * $brcm_Workfile: bchp_decode_mcom_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 7/17/09 8:05p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jul 17 19:42:36 2009
 *                 MD5 Checksum         2914699efc3fb3edefca5cb4f4f38b34
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/70015/rdb/a0/bchp_decode_mcom_0.h $
 * 
 * Hydra_Software_Devel/1   7/17/09 8:05p albertl
 * PR56880: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_DECODE_MCOM_0_H__
#define BCHP_DECODE_MCOM_0_H__

/***************************************************************************
 *DECODE_MCOM_0
 ***************************************************************************/
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL          0x00800300 /* Motion Compensation Control */
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_A        0x00800304 /* Motion Compensation Source A */
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_B        0x00800308 /* Motion Compensation Source */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC      0x0080030c /* VC-1 Mocomp  Picture-Level Control */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC  0x00800310 /* VC-1 Mocomp Bottom Pic */
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL          0x00800314 /* Weighted Prediction Selection */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC 0x00800318 /* VC-1 Mocomp Back Pic */
#define BCHP_DECODE_MCOM_0_REG_MCOM_END          0x0080031c /* REG_MCOM_END */

/***************************************************************************
 *REG_MCOM_CTL - Motion Compensation Control
 ***************************************************************************/
/* DECODE_MCOM_0 :: REG_MCOM_CTL :: Bintl [31:31] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Bintl_MASK                 0x80000000
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Bintl_SHIFT                31

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: Bref [30:24] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Bref_MASK                  0x7f000000
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Bref_SHIFT                 24

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: Aintl [23:23] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Aintl_MASK                 0x00800000
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Aintl_SHIFT                23

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: ARef [22:16] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_ARef_MASK                  0x007f0000
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_ARef_SHIFT                 16

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: SubBlock [15:12] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_SubBlock_MASK              0x0000f000
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_SubBlock_SHIFT             12

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: BBot [11:11] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_BBot_MASK                  0x00000800
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_BBot_SHIFT                 11

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: BFld [10:10] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_BFld_MASK                  0x00000400
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_BFld_SHIFT                 10

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: ABot [09:09] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_ABot_MASK                  0x00000200
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_ABot_SHIFT                 9

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: AFld [08:08] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_AFld_MASK                  0x00000100
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_AFld_SHIFT                 8

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: YSize [07:06] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_YSize_MASK                 0x000000c0
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_YSize_SHIFT                6

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: XSize [05:04] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_XSize_MASK                 0x00000030
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_XSize_SHIFT                4

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: Luma [03:03] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Luma_MASK                  0x00000008
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Luma_SHIFT                 3

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: Filter261 [02:02] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Filter261_MASK             0x00000004
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Filter261_SHIFT            2

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: Mde [01:01] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Mde_MASK                   0x00000002
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Mde_SHIFT                  1

/* DECODE_MCOM_0 :: REG_MCOM_CTL :: Back [00:00] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Back_MASK                  0x00000001
#define BCHP_DECODE_MCOM_0_REG_MCOM_CTL_Back_SHIFT                 0

/***************************************************************************
 *REG_MCOM_SRC_A - Motion Compensation Source A
 ***************************************************************************/
/* DECODE_MCOM_0 :: REG_MCOM_SRC_A :: YSrc [31:16] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_A_YSrc_MASK                0xffff0000
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_A_YSrc_SHIFT               16

/* DECODE_MCOM_0 :: REG_MCOM_SRC_A :: XSrc [15:00] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_A_XSrc_MASK                0x0000ffff
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_A_XSrc_SHIFT               0

/***************************************************************************
 *REG_MCOM_SRC_B - Motion Compensation Source
 ***************************************************************************/
/* DECODE_MCOM_0 :: REG_MCOM_SRC_B :: YSrc [31:16] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_B_YSrc_MASK                0xffff0000
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_B_YSrc_SHIFT               16

/* DECODE_MCOM_0 :: REG_MCOM_SRC_B :: XSrc [15:00] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_B_XSrc_MASK                0x0000ffff
#define BCHP_DECODE_MCOM_0_REG_MCOM_SRC_B_XSrc_SHIFT               0

/***************************************************************************
 *REG_WPRD_VC1_PIC - VC-1 Mocomp  Picture-Level Control
 ***************************************************************************/
/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: reserved0 [31:30] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_reserved0_MASK         0xc0000000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_reserved0_SHIFT        30

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: ALT_PAD [29:29] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_ALT_PAD_MASK           0x20000000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_ALT_PAD_SHIFT          29

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: reserved1 [28:28] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_reserved1_MASK         0x10000000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_reserved1_SHIFT        28

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: SHIFT2 [27:22] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_SHIFT2_MASK            0x0fc00000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_SHIFT2_SHIFT           22

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: SCALE2 [21:16] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_SCALE2_MASK            0x003f0000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_SCALE2_SHIFT           16

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: SHIFT1 [15:10] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_SHIFT1_MASK            0x0000fc00
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_SHIFT1_SHIFT           10

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: SCALE1 [09:04] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_SCALE1_MASK            0x000003f0
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_SCALE1_SHIFT           4

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: reserved2 [03:02] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_reserved2_MASK         0x0000000c
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_reserved2_SHIFT        2

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: BICUBIC [01:01] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_BICUBIC_MASK           0x00000002
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_BICUBIC_SHIFT          1

/* DECODE_MCOM_0 :: REG_WPRD_VC1_PIC :: RND [00:00] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_RND_MASK               0x00000001
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_PIC_RND_SHIFT              0

/***************************************************************************
 *REG_WPRD_VC1_BOT_PIC - VC-1 Mocomp Bottom Pic
 ***************************************************************************/
/* DECODE_MCOM_0 :: REG_WPRD_VC1_BOT_PIC :: reserved0 [31:28] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_reserved0_MASK     0xf0000000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_reserved0_SHIFT    28

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BOT_PIC :: SHIFT2 [27:22] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_SHIFT2_MASK        0x0fc00000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_SHIFT2_SHIFT       22

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BOT_PIC :: SCALE2 [21:16] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_SCALE2_MASK        0x003f0000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_SCALE2_SHIFT       16

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BOT_PIC :: SHIFT1 [15:10] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_SHIFT1_MASK        0x0000fc00
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_SHIFT1_SHIFT       10

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BOT_PIC :: SCALE1 [09:04] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_SCALE1_MASK        0x000003f0
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_SCALE1_SHIFT       4

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BOT_PIC :: reserved1 [03:00] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_reserved1_MASK     0x0000000f
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BOT_PIC_reserved1_SHIFT    0

/***************************************************************************
 *REG_WPRD_SEL - Weighted Prediction Selection
 ***************************************************************************/
/* DECODE_MCOM_0 :: REG_WPRD_SEL :: reserved0 [31:30] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_reserved0_MASK             0xc0000000
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_reserved0_SHIFT            30

/* DECODE_MCOM_0 :: REG_WPRD_SEL :: VecAWtSel0 [29:25] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_VecAWtSel0_MASK            0x3e000000
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_VecAWtSel0_SHIFT           25

/* DECODE_MCOM_0 :: REG_WPRD_SEL :: VecBWtSel0 [24:16] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_VecBWtSel0_MASK            0x01ff0000
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_VecBWtSel0_SHIFT           16

/* DECODE_MCOM_0 :: REG_WPRD_SEL :: Wt1 [15:15] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_Wt1_MASK                   0x00008000
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_Wt1_SHIFT                  15

/* DECODE_MCOM_0 :: REG_WPRD_SEL :: reserved1 [14:14] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_reserved1_MASK             0x00004000
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_reserved1_SHIFT            14

/* DECODE_MCOM_0 :: REG_WPRD_SEL :: VecAWtSel1 [13:09] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_VecAWtSel1_MASK            0x00003e00
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_VecAWtSel1_SHIFT           9

/* DECODE_MCOM_0 :: REG_WPRD_SEL :: VecBWtSel1 [08:00] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_VecBWtSel1_MASK            0x000001ff
#define BCHP_DECODE_MCOM_0_REG_WPRD_SEL_VecBWtSel1_SHIFT           0

/***************************************************************************
 *REG_WPRD_VC1_BACK_PIC - VC-1 Mocomp Back Pic
 ***************************************************************************/
/* DECODE_MCOM_0 :: REG_WPRD_VC1_BACK_PIC :: reserved0 [31:16] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_reserved0_MASK    0xffff0000
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_reserved0_SHIFT   16

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BACK_PIC :: Shift1 [15:10] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_Shift1_MASK       0x0000fc00
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_Shift1_SHIFT      10

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BACK_PIC :: Scale1 [09:04] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_Scale1_MASK       0x000003f0
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_Scale1_SHIFT      4

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BACK_PIC :: reserved1 [03:01] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_reserved1_MASK    0x0000000e
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_reserved1_SHIFT   1

/* DECODE_MCOM_0 :: REG_WPRD_VC1_BACK_PIC :: Bot [00:00] */
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_Bot_MASK          0x00000001
#define BCHP_DECODE_MCOM_0_REG_WPRD_VC1_BACK_PIC_Bot_SHIFT         0

/***************************************************************************
 *REG_MCOM_END - REG_MCOM_END
 ***************************************************************************/
/* DECODE_MCOM_0 :: REG_MCOM_END :: reserved0 [31:00] */
#define BCHP_DECODE_MCOM_0_REG_MCOM_END_reserved0_MASK             0xffffffff
#define BCHP_DECODE_MCOM_0_REG_MCOM_END_reserved0_SHIFT            0

#endif /* #ifndef BCHP_DECODE_MCOM_0_H__ */

/* End of File */
