/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 **********************************************************************
 * This file is part of the crystalhd device driver.
 *
 * This driver is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * This driver is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this driver.  If not, see <http://www.gnu.org/licenses/>.
 **********************************************************************
 *
 * $brcm_Workfile: bchp_pri_arb_wrch_regs.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 7/17/09 8:15p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jul 17 19:42:44 2009
 *                 MD5 Checksum         2914699efc3fb3edefca5cb4f4f38b34
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/70015/rdb/a0/bchp_pri_arb_wrch_regs.h $
 * 
 * Hydra_Software_Devel/1   7/17/09 8:15p albertl
 * PR56880: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_PRI_ARB_WRCH_REGS_H__
#define BCHP_PRI_ARB_WRCH_REGS_H__

/***************************************************************************
 *PRI_ARB_WRCH_REGS - PRIMARY_ARB secure wrch control registers
 ***************************************************************************/
#define BCHP_PRI_ARB_WRCH_REGS_RESERVED0         0x00461000 /* Reserved */
#define BCHP_PRI_ARB_WRCH_REGS_RESERVED1         0x004610fc /* Reserved */

/***************************************************************************
 *RESERVED0 - Reserved
 ***************************************************************************/
/* PRI_ARB_WRCH_REGS :: RESERVED0 :: RESERVED [31:00] */
#define BCHP_PRI_ARB_WRCH_REGS_RESERVED0_RESERVED_MASK             0xffffffff
#define BCHP_PRI_ARB_WRCH_REGS_RESERVED0_RESERVED_SHIFT            0

/***************************************************************************
 *RESERVED1 - Reserved
 ***************************************************************************/
/* PRI_ARB_WRCH_REGS :: RESERVED1 :: RESERVED [31:00] */
#define BCHP_PRI_ARB_WRCH_REGS_RESERVED1_RESERVED_MASK             0xffffffff
#define BCHP_PRI_ARB_WRCH_REGS_RESERVED1_RESERVED_SHIFT            0

#endif /* #ifndef BCHP_PRI_ARB_WRCH_REGS_H__ */

/* End of File */
